name: example

on: push
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: get repo
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello Patrick